src/include/tango/server/fwdattribute.h: Silence bugprone-tagged-union-member-count clang-tidy warning
We get the following warning from clang-tidy-20:

/builds/tango-controls/cppTango/src/include/tango/server/fwdattribute.h:44:7: error: tagged union has more data members (13) than tags (5)! [bugprone-tagged-union-member-count,-warnings-as-errors]
   44 | class FwdAttribute : public WAttribute

A tagged union is defined according to [1] as

> A struct or a class is considered to be a tagged union if it has exactly
> one union data member and exactly one enum data member and any number of
> other data members that are neither unions or enums.

But we don't have that in this case here. So let's ignore the warning.

[1]: https://clang.llvm.org/extra/clang-tidy/checks/bugprone/tagged-union-member-count.html