zmqeventconsumer.cpp: Avoid unused-result warning
Compiling with C++17 shows a couple of the following warnings:

/builds/[MASKED]/cppTango/src/client/zmqeventconsumer.cpp:4167:24: error: ignoring return value of 'zmq::recv_result_t zmq::detail::socket_base::recv(zmq::message_t&, zmq::recv_flags)', declared with attribute 'nodiscard' [-Werror=unused-result]
 4167 |             sender.recv(reply);
      |             ~~~~~~~~~~~^~~~~~~
/usr/include/zmq.hpp:2010:19: note: declared here
 2010 |     recv_result_t recv(message_t &msg, recv_flags flags = recv_flags::none)
      |                   ^~~~
[ 24%] Building CXX object src/server/CMakeFiles/server_objects.dir/utils_shut.cpp.o

Let's fix those and add an assertion instead of ignoring the warning.