treewide: Prefer const reference when possible
This fixes the clang-tidy warning:

  error: the variable 'XXX' is copy-constructed from a const reference but
  is only used as const reference; consider making it a const reference
  [performance-unnecessary-copy-initialization,-warnings-as-errors]