treewide: Prefer parantheses when combining different operators
This is more readable and fixes the following clang-tidy warning:

  error: '*' has higher precedence than '+'; add parentheses to explicitly
  specify the order of operations [readability-math-missing-parentheses,-warnings-as-errors]