configure/CMakeLists.txt: Fix libcpp CI job
This currently fails due to errors like [1]

d.lld: error: undefined reference due to --no-allow-shlib-undefined: opentelemetry::v1::sdk::trace::TracerProvider::ForceFlush(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>)
>>> referenced by ../libtango.so.10.0.0dev
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: opentelemetry::v1::exporter::otlp::GetOtlpDefaultHttpLogsEndpoint()
>>> referenced by ../libtango.so.10.0.0dev
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: opentelemetry::v1::exporter::otlp::GetOtlpDefaultLogsHeaders()

The reason for these are because we use libc++ as C++ standard library in
the libcpp job but have compiled all libraries against libstd++ and that
makes a difference as GCC still uses the abi:cxx11 tag as can be seen in

nm -A --demangle /usr/local/lib/libopentelemetry_* | grep GetOtlpDefaultGrpcTracesEndpoint | grep -i "T "
/usr/local/lib/libopentelemetry_otlp_recordable.so:000000000000b070 T opentelemetry::v1::exporter::otlp::GetOtlpDefaultGrpcTracesEndpoint[abi:cxx11]()

Other linkers default to --allow-shlib-undefined so we also allow it here.

[1]: https://gitlab.com/tango-controls/cppTango/-/jobs/6233935390